# fly.toml file generated for cold-paper-369 on 2022-11-09T18:54:54+08:00

app = "cold-paper-369"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8081
  HOST = "https://cold-paper-369.fly.dev/"
  SHOPIFY_API_KEY = "58563dafd0e1be3ab2c74529e4f23514"
  SCOPES = "write_products"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
